// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: sf/ethereum/statedb/v1/singlet.proto

package pbstatedb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Balance represents the Wei value in hexadecimal format that can be used to
	// create a `math.BigInt` instance.
	Balance []byte `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *BalanceValue) Reset() {
	*x = BalanceValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_ethereum_statedb_v1_singlet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceValue) ProtoMessage() {}

func (x *BalanceValue) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_statedb_v1_singlet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceValue.ProtoReflect.Descriptor instead.
func (*BalanceValue) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_statedb_v1_singlet_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceValue) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

type NonceValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *NonceValue) Reset() {
	*x = NonceValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_ethereum_statedb_v1_singlet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NonceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonceValue) ProtoMessage() {}

func (x *NonceValue) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_statedb_v1_singlet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonceValue.ProtoReflect.Descriptor instead.
func (*NonceValue) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_statedb_v1_singlet_proto_rawDescGZIP(), []int{1}
}

func (x *NonceValue) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type StateValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StateValue) Reset() {
	*x = StateValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_ethereum_statedb_v1_singlet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateValue) ProtoMessage() {}

func (x *StateValue) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_statedb_v1_singlet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateValue.ProtoReflect.Descriptor instead.
func (*StateValue) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_statedb_v1_singlet_proto_rawDescGZIP(), []int{2}
}

func (x *StateValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CodeValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CodeValue) Reset() {
	*x = CodeValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_ethereum_statedb_v1_singlet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeValue) ProtoMessage() {}

func (x *CodeValue) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_statedb_v1_singlet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeValue.ProtoReflect.Descriptor instead.
func (*CodeValue) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_statedb_v1_singlet_proto_rawDescGZIP(), []int{3}
}

func (x *CodeValue) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_sf_ethereum_statedb_v1_singlet_proto protoreflect.FileDescriptor

var file_sf_ethereum_statedb_v1_singlet_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x66, 0x2f, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x73, 0x66, 0x2e, 0x65, 0x74, 0x68, 0x65, 0x72,
	0x65, 0x75, 0x6d, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x22, 0x28,
	0x0a, 0x0c, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x22, 0x0a, 0x0a, 0x4e, 0x6f, 0x6e, 0x63,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x22, 0x0a, 0x0a,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x25, 0x0a, 0x09, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x4b, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x66,
	0x61, 0x73, 0x74, 0x2f, 0x65, 0x76, 0x6d, 0x2d, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72,
	0x2f, 0x70, 0x62, 0x2f, 0x73, 0x66, 0x2f, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x62, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x64, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sf_ethereum_statedb_v1_singlet_proto_rawDescOnce sync.Once
	file_sf_ethereum_statedb_v1_singlet_proto_rawDescData = file_sf_ethereum_statedb_v1_singlet_proto_rawDesc
)

func file_sf_ethereum_statedb_v1_singlet_proto_rawDescGZIP() []byte {
	file_sf_ethereum_statedb_v1_singlet_proto_rawDescOnce.Do(func() {
		file_sf_ethereum_statedb_v1_singlet_proto_rawDescData = protoimpl.X.CompressGZIP(file_sf_ethereum_statedb_v1_singlet_proto_rawDescData)
	})
	return file_sf_ethereum_statedb_v1_singlet_proto_rawDescData
}

var file_sf_ethereum_statedb_v1_singlet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sf_ethereum_statedb_v1_singlet_proto_goTypes = []interface{}{
	(*BalanceValue)(nil), // 0: sf.ethereum.statedb.v1.BalanceValue
	(*NonceValue)(nil),   // 1: sf.ethereum.statedb.v1.NonceValue
	(*StateValue)(nil),   // 2: sf.ethereum.statedb.v1.StateValue
	(*CodeValue)(nil),    // 3: sf.ethereum.statedb.v1.CodeValue
}
var file_sf_ethereum_statedb_v1_singlet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sf_ethereum_statedb_v1_singlet_proto_init() }
func file_sf_ethereum_statedb_v1_singlet_proto_init() {
	if File_sf_ethereum_statedb_v1_singlet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sf_ethereum_statedb_v1_singlet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_ethereum_statedb_v1_singlet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NonceValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_ethereum_statedb_v1_singlet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_ethereum_statedb_v1_singlet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sf_ethereum_statedb_v1_singlet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_ethereum_statedb_v1_singlet_proto_goTypes,
		DependencyIndexes: file_sf_ethereum_statedb_v1_singlet_proto_depIdxs,
		MessageInfos:      file_sf_ethereum_statedb_v1_singlet_proto_msgTypes,
	}.Build()
	File_sf_ethereum_statedb_v1_singlet_proto = out.File
	file_sf_ethereum_statedb_v1_singlet_proto_rawDesc = nil
	file_sf_ethereum_statedb_v1_singlet_proto_goTypes = nil
	file_sf_ethereum_statedb_v1_singlet_proto_depIdxs = nil
}
